[uwsgi]
module = app:APP
chdir = /home/www/html/cc-worker-api
master = true
processes = 2
threads = 4
http = 127.0.0.1:5001
vacuum = true
die-on-term = true
pidfile = /home/www/html/cc-worker-api/uwsgi.pid
logto = /home/www/html/cc-worker-api/uwsgi.log
buffer-size = 65535
http-timeout = 600
socket-timeout = 600
